version: "3.8"

services:
  charts:
    build:
      context: .
      dockerfile: Dockerfile.dash
    image: poc-genie-charts-dev:local
    environment:
      - BOT_URL=https://poc-genie-web-app-hwerdjfpauehcxa4.eastus-01.azurewebsites.net
      - DASH_PORT=8050
    ports:
      - "8050:8050"