name: Build and deploy Python app to Azure Web App - POC-genie-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # (Optional) install & run tests here
      # - name: Install dependencies
      #   run: pip install --upgrade pip && pip install -r requirements.txt
      # - name: Run tests
      #   run: pytest

      - name: Zip source for Run‑From‑Package
        run: |
          zip -r release.zip . \
            -x ".git/*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x "venv/*" \
            -x ".venv/*" \
            -x ".env*" \
            -x "docs/*" \
            -x "tests/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App (Run‑From‑Package)
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'POC-genie-web-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB7A030785BB4A8DBFC44036C84F6519 }}
          package: release.zip