name: Deploy Python app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Zip source
        run: |
          zip -r release.zip . \
            -x ".git/*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x "venv/*" \
            -x ".venv/*" \
            -x ".env*" \
            -x "docs/*" \
            -x "tests/*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with: { name: python-app }

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "POC-genie-web-app"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EB7A030785BB4A8DBFC44036C84F6519 }}
          package: release.zip
          clean: false
